@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=api
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

# GET /all

### GET/perfumes
GET {{baseUrl}}/perfumes

### GET/genders
GET {{baseUrl}}/genders

### GET/intensities
GET {{baseUrl}}/intensities

### GET/scents
GET {{baseUrl}}/scents

### GET/tags
GET {{baseUrl}}/tags

# GET /:id

### GET/perfumes/:id
GET {{baseUrl}}/perfumes/2

### GET/genders/:id
GET {{baseUrl}}/genders/4

### GET/intensities/:id
GET {{baseUrl}}/intensities/2

### GET/scents/:id
GET {{baseUrl}}/scents/3

### GET/tag/:id
GET {{baseUrl}}/tags/3